{{- $name := .Values.name -}}
{{- $svcPort := .Values.service.port -}}

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $name }}"
  namespace: api
  labels:
    app.kubernetes.io/instance: "{{ $name }}"
    app.kubernetes.io/name: "{{ $name }}"
spec:
  type: ClusterIP
  ports:
    - port: {{ $svcPort}}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "{{ $name }}"
    app.kubernetes.io/instance: "{{ $name }}"
