apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: api
  labels:
    {{- include "api-helm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "api-helm.selectorLabels" . | nindent 4 }}
