apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-hello-routes
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/routes
    repoURL: 'https://github.com/automate-cloud-poc/control-tower'
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../../api/api-argo-hello/routes.yml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - Replace=true
