{{- if .Values.sealedSecret }}
{{- $name := .Values.name -}}

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "sealed-{{ .Values.name }}"
  namespace: api
spec:
  encryptedData:
  {{- range $key,$value := .Values.sealedSecret }}
    {{$key}}: {{$value}}
  {{- end }}

{{- end }}