{{- $name := .Values.name -}}
{{- $replicaCount := .Values.deploy.replicaCount -}}
{{- $repo := .Values.deploy.image.repository -}}
{{- $svcPort := .Values.service.port -}}
{{- $configMap := .Values.configMap -}}
{{- $sealedSecret := .Values.sealedSecret -}}

{{- range $canaryHeader := .Values.canaryHeader }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $name }}-{{substr 0 7 $canaryHeader.commit}}"
  namespace: api
  labels:
    app.kubernetes.io/instance: "{{ $name }}-{{substr 0 7 $canaryHeader.commit}}"
    app.kubernetes.io/name: "{{ $name }}-{{substr 0 7 $canaryHeader.commit}}"
spec:
  replicas: {{ $replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: "{{ $name }}-{{substr 0 7 $canaryHeader.commit}}"
      app.kubernetes.io/name: "{{ $name }}-{{substr 0 7 $canaryHeader.commit}}"
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: "{{ $name }}-{{substr 0 7 $canaryHeader.commit}}"
        app.kubernetes.io/name: "{{ $name }}-{{substr 0 7 $canaryHeader.commit}}"
    spec:
      containers:
        - name: "{{ $name }}-{{substr 0 7 $canaryHeader.commit}}"
          image: "{{ $repo }}:{{$canaryHeader.commit}}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ $svcPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          {{- if or $configMap $sealedSecret}}
          envFrom:
            {{- if $configMap}}
            - configMapRef:
                name: "{{ $name }}-configmap"
            {{- end }}
            {{- if $sealedSecret}}
            - secretRef:
                name: "{{ $name }}"
        {{- end }}
  {{- end }}
{{- end }}