{{- $name := .Values.name -}}
{{- $replicaCount := .Values.deploy.replicaCount -}}
{{- $repo := .Values.deploy.image.repository -}}
{{- $svcPort := .Values.service.port -}}

{{- range $canaryHeader := .Values.canaryHeader }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $name }}-{{$canaryHeader.commit}}"
  namespace: api
  labels:
    - "{{ $name }}-{{$canaryHeader.commit}}"
spec:
  replicas: {{ $replicaCount }}
  selector:
    matchLabels:
      - "{{ $name }}-{{$canaryHeader.commit}}"
  template:
    metadata:
      labels:
        - "{{ $name }}-{{$canaryHeader.commit}}"
    spec:
      containers:
        - name: "{{ $name }}-{{$canaryHeader.commit}}"
          image: "{{ $repo }}@sha256:{{$canaryHeader.commit}}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ $svcPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
{{- end }}