{{- $name := .Values.name -}}
{{- $svcPort := .Values.service.port -}}

{{- range $canaryHeader := .Values.canaryHeader }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $name }}-{{substr 0 7 $canaryHeader.commit}}"
  namespace: api
  labels:
    app.kubernetes.io/instance: "{{ $name }}-{{substr 0 7 $canaryHeader.commit}}"
spec:
  type: ClusterIP
  ports:
    - port: {{ $svcPort}}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "{{ $name }}-{{substr 0 7 $canaryHeader.commit}}"
    app.kubernetes.io/instance: "{{ $name }}-{{substr 0 7 $canaryHeader.commit}}"
{{- end }}