{{- $name := .Values.name -}}
{{- $svcPort := .Values.service.port -}}

{{- range $canaryHeader := .Values.canaryHeader }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $name }}-{{$canaryHeader.commit}}"
  namespace: api
  labels:
    {{- include "api-helm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $svcPort}}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "api-helm.selectorLabels" . | nindent 4 }}
{{- end }}