{{- if .Values.gateway }}

{{- $svcPort := .Values.gateway.port -}}
{{- $name := .Values.name -}}

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "external-{{ .Values.name }}"
  namespace: api
spec:
  hosts:
    - '*'
  gateways:
    - gateway/edge-ingress
  http:
    {{- range $route := .Values.gateway.routes }}
    - match:
      - uri:

        {{- if $route.path }}
          exact: "{{ $route.path }}"
        {{- end }}

        {{- if $route.prefix }}
          prefix: "{{ $route.prefix }}"
        {{- end }}

      rewrite:
        authority: "{{ $name }}.api.svc.cluster.local"
      route:
        - destination:
          {{- if .auth }}
            port:
              number: {{ $svcPort }}
            host: "{{ .auth }}.api.svc.cluster.local"
          {{- else }}
            port:
              number: 80
            host: "internal-ingress.gateway.svc.cluster.local"
          {{- end }}
  {{- end }}

{{- end }}