{{- if .Values.gateway }}

{{- $svcPort := .Values.gateway.port -}}
{{- $name := .Values.name -}}
{{- $routes := .Values.gateway.routes -}}

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "internal-{{ .Values.name }}"
  namespace: api
spec:
  hosts:
    - "{{ $name }}.api.svc.cluster.local"
  gateways:
    - gateway/internal-ingress
  http:
    {{- if .Values.canaryHeader }}
    {{- range $canaryHeader := .Values.canaryHeader }}
    {{- range $route := $routes }}
    - match:
        - uri:
            exact: "{{ $route.path }}"
          headers:
            {{$canaryHeader.header.key}}:
              exact: "{{$canaryHeader.header.value}}"
      route:
        - destination:
            port:
              number: {{ $svcPort }}
            host: "{{ $name }}-{{substr 0 7 $canaryHeader.commit}}.api.svc.cluster.local"
    {{- end }}
    {{- end }}
    {{- end }}

    {{- range $route := .Values.gateway.routes }}
    - match:
        - uri:
            exact: "{{ $route.path }}"
      route:
        - destination:
            port:
              number: {{ $svcPort }}
            host: "{{ $name }}.api.svc.cluster.local"
  {{- end }}

{{- end }}