{{- if .Values.gateway }}

{{- $svcPort := .Values.gateway.port -}}
{{- $name := .Values.name -}}

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "internal-{{ .Values.name }}"
  namespace: api
spec:
  hosts:
    - "{{ $name }}.api.svc.cluster.local"
  gateways:
    - gateway/internal-ingress
  http:
    {{- range .Values.gateway.routes }}
    - match:
        - uri:
            exact: "{{ .path }}"
      route:
        - destination:
            port:
              number: {{ $svcPort }}
            host: "{{ $name }}.api.svc.cluster.local"
  {{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "external-{{ .Values.name }}"
  namespace: api
spec:
  hosts:
    - '*'
  gateways:
    - gateway/edge-ingress
  http:
    {{- range .Values.gateway.routes }}
    - match:
      - uri:
          exact: "{{ .path }}"
      rewrite:
        authority: "{{ $name }}.api.svc.cluster.local"
      route:
        - destination:
            port:
              number: {{ $svcPort }}
          {{- if .auth }}
            host: "{{ .auth }}.api.svc.cluster.local"
          {{- else }}
            host: "{{ $name }}.api.svc.cluster.local"
          {{- end }}
  {{- end }}

{{- end }}