applications:
  - name: "api-argo-hello"
    deploy:
      ApplyOutOfSyncOnly: true
    routes:
      ApplyOutOfSyncOnly: true
    routesHeader:
      ApplyOutOfSyncOnly: true
  - name: "api-auth-v1"
    deploy:
      ApplyOutOfSyncOnly: true
    routes:
      ApplyOutOfSyncOnly: true
    routesHeader:
      ApplyOutOfSyncOnly: true